#!/usr/bin/env bash
# This is post_cargo_install_hook

# when cargo was called with install as first argument, reshim
echo "Post Cargo Install :: ASDF Reshim"

if [ "install" == "$1" ] ; then
   asdf reshim rust
fi
